# -*- coding: utf-8 -*-
"""
daily_lineup.py
----------------
Auto-generated by fetch_lineups.py on 2026-05-11
Source: MLB Stats API + lineup cache
"""

from datetime import date

TODAY = "2026-05-11"

# Teams with no pitcher posted today
NO_PITCHER_TEAMS = ['LAA']

# Teams using yesterday's confirmed lineup
CARRIED_LINEUP_TEAMS = ['AZ', 'BAL', 'CLE', 'HOU', 'LAA', 'LAD', 'NYY', 'SEA', 'SF', 'TB', 'TEX', 'TOR']

# Teams using fallback hardcoded roster
FALLBACK_LINEUP_TEAMS = []

GAME_TIMES_UTC = {
    "BAL": "2026-05-11T22:35:00Z",
    "CLE": "2026-05-11T22:10:00Z",
    "HOU": "2026-05-12T00:10:00Z",
    "LAD": "2026-05-12T02:10:00Z",
    "TEX": "2026-05-12T00:05:00Z",
    "TOR": "2026-05-11T23:07:00Z",
}

TODAYS_STARTERS = {
    "AZ": {"name": "Michael Soroka", "hand": "R", "role": "starter"},
    "BAL": {"name": "Brandon Young", "hand": "R", "role": "starter"},
    "CLE": {"name": "Joey Cantillo", "hand": "R", "role": "starter"},
    "HOU": {"name": "Peter Lambert", "hand": "R", "role": "starter"},
    "LAD": {"name": "Roki Sasaki", "hand": "R", "role": "starter"},
    "NYY": {"name": "Ryan Weathers", "hand": "R", "role": "starter"},
    "SEA": {"name": "George Kirby", "hand": "R", "role": "starter"},
    "SF": {"name": "Trevor McDonald", "hand": "R", "role": "starter"},
    "TB": {"name": "Drew Rasmussen", "hand": "R", "role": "starter"},
    "TEX": {"name": "Nathan Eovaldi", "hand": "R", "role": "starter"},
    "TOR": {"name": "Kevin Gausman", "hand": "R", "role": "starter"},
}

BULLPEN_AVAILABILITY = {
}

TODAYS_LINEUPS = {
    "AZ": [
        {"order": 1, "name": "Ketel Marte", "bats": "R", "pos": "2B"}, 
        {"order": 2, "name": "Corbin Carroll", "bats": "R", "pos": "RF"}, 
        {"order": 3, "name": "Geraldo Perdomo", "bats": "R", "pos": "SS"}, 
        {"order": 4, "name": "Adrian Del Castillo", "bats": "R", "pos": "DH"}, 
        {"order": 5, "name": "Ildemaro Vargas", "bats": "R", "pos": "1B"}, 
        {"order": 6, "name": "Nolan Arenado", "bats": "R", "pos": "3B"}, 
        {"order": 7, "name": "James McCann", "bats": "R", "pos": "C"}, 
        {"order": 8, "name": "Jorge Barrosa", "bats": "R", "pos": "CF"}, 
        {"order": 9, "name": "Ryan Waldschmidt", "bats": "R", "pos": "LF"}, 
    ],
    "BAL": [
        {"order": 1, "name": "Gunnar Henderson", "bats": "R", "pos": "SS"}, 
        {"order": 2, "name": "Taylor Ward", "bats": "R", "pos": "LF"}, 
        {"order": 3, "name": "Adley Rutschman", "bats": "R", "pos": "DH"}, 
        {"order": 4, "name": "Pete Alonso", "bats": "R", "pos": "1B"}, 
        {"order": 5, "name": "Samuel Basallo", "bats": "R", "pos": "C"}, 
        {"order": 6, "name": "Leody Taveras", "bats": "R", "pos": "CF"}, 
        {"order": 7, "name": "Dylan Beavers", "bats": "R", "pos": "RF"}, 
        {"order": 8, "name": "Weston Wilson", "bats": "R", "pos": "3B"}, 
        {"order": 9, "name": "Blaze Alexander", "bats": "R", "pos": "2B"}, 
    ],
    "CLE": [
        {"order": 1, "name": "Steven Kwan", "bats": "R", "pos": "CF"}, 
        {"order": 2, "name": "Chase DeLauter", "bats": "R", "pos": "RF"}, 
        {"order": 3, "name": "José Ramírez", "bats": "R", "pos": "DH"}, 
        {"order": 4, "name": "Kyle Manzardo", "bats": "R", "pos": "1B"}, 
        {"order": 5, "name": "Daniel Schneemann", "bats": "R", "pos": "3B"}, 
        {"order": 6, "name": "Angel Martínez", "bats": "R", "pos": "LF"}, 
        {"order": 7, "name": "Travis Bazzana", "bats": "R", "pos": "2B"}, 
        {"order": 8, "name": "Patrick Bailey", "bats": "R", "pos": "C"}, 
        {"order": 9, "name": "Brayan Rocchio", "bats": "R", "pos": "SS"}, 
    ],
    "HOU": [
        {"order": 1, "name": "Jose Altuve", "bats": "R", "pos": "2B"}, 
        {"order": 2, "name": "Yordan Alvarez", "bats": "R", "pos": "DH"}, 
        {"order": 3, "name": "Isaac Paredes", "bats": "R", "pos": "3B"}, 
        {"order": 4, "name": "Christian Walker", "bats": "R", "pos": "1B"}, 
        {"order": 5, "name": "Cam Smith", "bats": "R", "pos": "RF"}, 
        {"order": 6, "name": "Brice Matthews", "bats": "R", "pos": "CF"}, 
        {"order": 7, "name": "Zach Cole", "bats": "R", "pos": "LF"}, 
        {"order": 8, "name": "Nick Allen", "bats": "R", "pos": "SS"}, 
        {"order": 9, "name": "César Salazar", "bats": "R", "pos": "C"}, 
    ],
    "LAA": [
        {"order": 1, "name": "Zach Neto", "bats": "R", "pos": "SS"}, 
        {"order": 2, "name": "Mike Trout", "bats": "R", "pos": "DH"}, 
        {"order": 3, "name": "Vaughn Grissom", "bats": "R", "pos": "3B"}, 
        {"order": 4, "name": "Jorge Soler", "bats": "R", "pos": "RF"}, 
        {"order": 5, "name": "Jo Adell", "bats": "R", "pos": "LF"}, 
        {"order": 6, "name": "Nolan Schanuel", "bats": "R", "pos": "1B"}, 
        {"order": 7, "name": "Oswald Peraza", "bats": "R", "pos": "2B"}, 
        {"order": 8, "name": "Sebastián Rivero", "bats": "R", "pos": "C"}, 
        {"order": 9, "name": "Bryce Teodosio", "bats": "R", "pos": "CF"}, 
    ],
    "LAD": [
        {"order": 1, "name": "Shohei Ohtani", "bats": "R", "pos": "DH"}, 
        {"order": 2, "name": "Freddie Freeman", "bats": "R", "pos": "1B"}, 
        {"order": 3, "name": "Andy Pages", "bats": "R", "pos": "CF"}, 
        {"order": 4, "name": "Kyle Tucker", "bats": "R", "pos": "RF"}, 
        {"order": 5, "name": "Max Muncy", "bats": "R", "pos": "3B"}, 
        {"order": 6, "name": "Alex Call", "bats": "R", "pos": "LF"}, 
        {"order": 7, "name": "Dalton Rushing", "bats": "R", "pos": "C"}, 
        {"order": 8, "name": "Hyeseong Kim", "bats": "R", "pos": "SS"}, 
        {"order": 9, "name": "Alex Freeland", "bats": "R", "pos": "2B"}, 
    ],
    "NYY": [
        {"order": 1, "name": "Trent Grisham", "bats": "R", "pos": "CF"}, 
        {"order": 2, "name": "Ben Rice", "bats": "R", "pos": "1B"}, 
        {"order": 3, "name": "Aaron Judge", "bats": "R", "pos": "DH"}, 
        {"order": 4, "name": "Cody Bellinger", "bats": "R", "pos": "LF"}, 
        {"order": 5, "name": "Jazz Chisholm Jr.", "bats": "R", "pos": "2B"}, 
        {"order": 6, "name": "Ryan McMahon", "bats": "R", "pos": "3B"}, 
        {"order": 7, "name": "José Caballero", "bats": "R", "pos": "SS"}, 
        {"order": 8, "name": "Spencer Jones", "bats": "R", "pos": "RF"}, 
        {"order": 9, "name": "J.C. Escarra", "bats": "R", "pos": "C"}, 
    ],
    "SEA": [
        {"order": 1, "name": "Brendan Donovan", "bats": "R", "pos": "3B"}, 
        {"order": 2, "name": "Julio Rodríguez", "bats": "R", "pos": "CF"}, 
        {"order": 3, "name": "Josh Naylor", "bats": "R", "pos": "1B"}, 
        {"order": 4, "name": "Cal Raleigh", "bats": "R", "pos": "C"}, 
        {"order": 5, "name": "Randy Arozarena", "bats": "R", "pos": "LF"}, 
        {"order": 6, "name": "Luke Raley", "bats": "R", "pos": "RF"}, 
        {"order": 7, "name": "J.P. Crawford", "bats": "R", "pos": "SS"}, 
        {"order": 8, "name": "Dominic Canzone", "bats": "R", "pos": "DH"}, 
        {"order": 9, "name": "Cole Young", "bats": "R", "pos": "2B"}, 
    ],
    "SF": [
        {"order": 1, "name": "Jung Hoo Lee", "bats": "R", "pos": "RF"}, 
        {"order": 2, "name": "Luis Arraez", "bats": "R", "pos": "2B"}, 
        {"order": 3, "name": "Casey Schmitt", "bats": "R", "pos": "1B"}, 
        {"order": 4, "name": "Rafael Devers", "bats": "R", "pos": "DH"}, 
        {"order": 5, "name": "Heliot Ramos", "bats": "R", "pos": "LF"}, 
        {"order": 6, "name": "Willy Adames", "bats": "R", "pos": "SS"}, 
        {"order": 7, "name": "Matt Chapman", "bats": "R", "pos": "3B"}, 
        {"order": 8, "name": "Drew Gilbert", "bats": "R", "pos": "CF"}, 
        {"order": 9, "name": "Jesus Rodriguez", "bats": "R", "pos": "C"}, 
    ],
    "TB": [
        {"order": 1, "name": "Chandler Simpson", "bats": "R", "pos": "LF"}, 
        {"order": 2, "name": "Junior Caminero", "bats": "R", "pos": "3B"}, 
        {"order": 3, "name": "Ben Williamson", "bats": "R", "pos": "2B"}, 
        {"order": 4, "name": "Yandy Díaz", "bats": "R", "pos": "DH"}, 
        {"order": 5, "name": "Ryan Vilade", "bats": "R", "pos": "1B"}, 
        {"order": 6, "name": "Cedric Mullins", "bats": "R", "pos": "CF"}, 
        {"order": 7, "name": "Jonny DeLuca", "bats": "R", "pos": "RF"}, 
        {"order": 8, "name": "Nick Fortes", "bats": "R", "pos": "C"}, 
        {"order": 9, "name": "Taylor Walls", "bats": "R", "pos": "SS"}, 
    ],
    "TEX": [
        {"order": 1, "name": "Brandon Nimmo", "bats": "R", "pos": "RF"}, 
        {"order": 2, "name": "Ezequiel Duran", "bats": "R", "pos": "2B"}, 
        {"order": 3, "name": "Corey Seager", "bats": "R", "pos": "SS"}, 
        {"order": 4, "name": "Josh Jung", "bats": "R", "pos": "3B"}, 
        {"order": 5, "name": "Evan Carter", "bats": "R", "pos": "CF"}, 
        {"order": 6, "name": "Joc Pederson", "bats": "R", "pos": "DH"}, 
        {"order": 7, "name": "Alejandro Osuna", "bats": "R", "pos": "LF"}, 
        {"order": 8, "name": "Danny Jansen", "bats": "R", "pos": "C"}, 
        {"order": 9, "name": "Justin Foscue", "bats": "R", "pos": "1B"}, 
    ],
    "TOR": [
        {"order": 1, "name": "Ernie Clement", "bats": "R", "pos": "2B"}, 
        {"order": 2, "name": "Daulton Varsho", "bats": "R", "pos": "CF"}, 
        {"order": 3, "name": "Vladimir Guerrero Jr.", "bats": "R", "pos": "DH"}, 
        {"order": 4, "name": "Kazuma Okamoto", "bats": "R", "pos": "3B"}, 
        {"order": 5, "name": "Jesús Sánchez", "bats": "R", "pos": "RF"}, 
        {"order": 6, "name": "Lenyn Sosa", "bats": "R", "pos": "1B"}, 
        {"order": 7, "name": "Andrés Giménez", "bats": "R", "pos": "SS"}, 
        {"order": 8, "name": "Myles Straw", "bats": "R", "pos": "LF"}, 
        {"order": 9, "name": "Tyler Heineman", "bats": "R", "pos": "C"}, 
    ],
}

SCRATCHES = []

GAME_TIMES = GAME_TIMES_UTC
